name: "Update Cluster Config pin for a cluster"

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: "Cluster name"
        required: true
        type: choice
        options:
          - hub

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Cluster Config checkout
        id: cluster-config-checkout
        uses: actions/checkout@v4
        with:
          repository: "puiterwijk-gitops/cluster-config"
          ref: "main"
          path: "cluster-config-repo"
          sparse-checkout: .
      - name: Print commit
        run: |
          echo "Commit: ${{ steps.cluster-config-checkout.outputs.commit }}"
      - name: Update pin
        run: |
          git checkout -b update-${{ github.job }}
          sed -i \
            's|github.com/puiterwijk-gitops/cluster-config/bootstrap/overlays/${{ github.event.inputs.cluster }}?ref=\([a-f0-9]\{40\}\)|github.com/puiterwijk-gitops/cluster-config/bootstrap/overlays/${{ github.event.inputs.cluster }}?ref=${{ steps.cluster-config-checkout.outputs.commit }}|' \
            bootstrap/overlays/${{ github.event.inputs.cluster }}/kustomization.yaml
          git add bootstrap/overlays/${{ github.event.inputs.cluster }}/kustomization.yaml
          git commit -m "Update pin for cluster ${{ github.event.inputs.cluster }} to ${{ steps.cluster-config-checkout.outputs.commit }}"
          git show HEAD
