name: Validate Manifests
on:
  #push:
  #  branches:
  #    - "*"
  pull_request:
    branches:
      - "*"

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Validate YAML
        uses: ibiqlik/action-yamllint@v3
        with:
          format: github
  lint-kustomize:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
      - name: Verify Kustomize CLI Installation
        run: |
          which kustomize
          kustomize version
      - name: Install Kustomize plugin for Open Policy Generator
        run: |
          mkdir -p ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator
          curl -Lo ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator https://github.com/open-cluster-management-io/policy-generator-plugin/releases/latest/download/linux-amd64-PolicyGenerator
          chmod +x ${HOME}/.config/kustomize/plugin/policy.open-cluster-management.io/v1/policygenerator/PolicyGenerator
      - name: Validate Manifests
        run: |
          ./scripts/validate_manifests.sh
